### ISSUE TITLE
Legend.from_csv errno22

### ISSUE THREAD

**Issue by alexcolyer** [agile-geoscience/striplog#112]
Hi,

I get an error when I am trying to follow the tutorial for making a legend. When I use the following code I get the [Errno 22] Invalid argument. However, I took most of the code from the tutorial, the only change I made was to remove duplicate legend items.

    from striplog import Legend, Lexicon, Interval, Component, Decor, Striplog

    l = u"""Colour, Component lithology
    #F7E9A6, Sandstone
    #FF99CC, Anhydrite
    #DBD6BC, Heterolithic 
    #FF4C4A, Volcanic
    #86F0B6, Conglomerate
    """
    legend = Legend.from_csv(l)

**Comment by kwinkunks** [comment]
It will try to interpret the first argument as a filename. You have to say, `legend = Legend.from_csv(text=l)`

**Comment by alexcolyer** [comment]
That is great, thanks
