### ISSUE TITLE
x-axis on lithology histogram

### ISSUE THREAD

**Issue by alexcolyer** [agile-geoscience/striplog#114]
The x-axis on the lithology histogram doesn't match the lithologies distribution. Instead, it plots the lithologies in order of occurrence.

![image](https://user-images.githubusercontent.com/44571638/80406142-803d8a00-88bb-11ea-9b43-30c2c47a4381.png)

**Comment by kwinkunks** [comment]
Thanks for posting - let me check into this Alex.

**Comment by kwinkunks** [comment]
Hi Alex... please update `striplog` from PyPi to version 0.8.4 and try:

![image](https://user-images.githubusercontent.com/1692372/80489935-f6330700-8936-11ea-959c-4de29fd52b06.png)

**Comment by kwinkunks** [comment]
I think this is fixed, @alexcolyer please let me know if we need to re-open.

**Comment by alexcolyer** [comment]
Hi Matt,

Yeah, the issue I raised has been fixed using your advise. Thanks,
Alex
