### ISSUE TITLE
Readthedocs - broken link (Striplog_object.ipynb)

### ISSUE THREAD

**Issue by ThirstyGeo** [agile-geoscience/striplog#123]
The userguide [page](https://striplog.readthedocs.io/en/latest/basic_objects.html) refers to a striplog object [example](https://striplog.readthedocs.io/en/latest/Striplog_object.ipynb) which no longer esists.

Possibly that example has been superceded by [this one](https://github.com/agile-geoscience/striplog/tree/master/tutorial/Basic_objects.ipynb)?

**Comment by mtb-za** [comment]
Fixed in #141.
