### ISSUE TITLE
Remove well-level code to another library

### ISSUE THREAD

**Issue by kwinkunks** [agile-geoscience/striplog#45]
Keep `striplog` to striplogs and make a new library: [welly](https://github.com/agile-geoscience/welly)

**Comment by kinverarity1** [comment]
Do you have any kind of ideas about what should belong where and a structure or scope for striplog and/or welly? 

I'm keen to fork and start working on a library for handling data at the well scale. I have an urgent need for it (need to quickly combine LAS file geophysics with strat logs in custom JSON format and produce a smartly-auto-scaled plot - probably matplotlib initially as that's what I have experience with). I suspect that you have a bunch of good stuff in striplog that I could start from...

**Comment by kwinkunks** [comment]
@kinverarity1 Great question. Short answer: I don't know.

I threw the well stuff into `striplog` to get a particular job done. But I have come to the conclusion that `striplog` should only do what it says on the tin — deal with striplogs.

The well-level stuff, which I see as using or wrapping your awesome [lasio](https://github.com/kinverarity1/lasio) project (probably not `las.py` as I have now), would help deal with I/O, headers, well paths (eg deviation), coordinates, etc. I'm not 100% sure `welly` is going to turn into that at this point, it was more of a way to get that stuff out of `striplog` for now. 100% happy for input on that, or taking it in another direction. My main need just now is to be able to read and write LAS 2.0 and, ideally, LAS 3.0 with my striplog stuff, ideally without substituting into templates as I was doing before. 

I think there's another package to be built around logs and petrophysics — log interpolation, unit conversion, smoothing (despiking, Backus averaging, etc), transforms (Gardner, Wyllie, etc), analysis, etc. That would potentially make a lot of use of [bruges](https://github.com/agile-geoscience/bruges).

The best way to see what `striplog` does is to look at the [Jupyter Notebooks in `/tutorial`](https://github.com/agile-geoscience/striplog/tree/master/tutorial). Maybe you can use some of that... I am just about to start another few months of work on it, so if you have requests, this is a great time for it... contributions also welcome of course :)

Thanks Kent!

**Comment by kinverarity1** [comment]
OK thanks - I did see those ``striplog`` tutorials and really like them. 

I'm trying to think through how a workflow might go...

```python
w = welly.Well()
w.add_las("geophysics.las")             # uses lasio internally
w.add_striplog("stratigraphy.csv")      # uses striplog internally
w.add_striplog("intervals.las")         # uses striplog which will use las.py or lasio
w.basic_log_manipulation()              # e.g. top_and_tail - should this be in welly or bruges? I thought welly.
w.more_complex_data_manipulation()      # e.g. petrophysics calculations - bruges
w.plot()                                # implemented in welly itself ??
w.write_las("export.las", version=3)    # use lasio once that has LAS 3 support
```

How do you envisage this kind of workflow?

I might try to come up with something like this in my ``welly`` fork - maybe borrow some of the plotting code from ``striplog``. I might also make ``welly.Well`` an object of its own rather than a subclass of ``las.LASReader`` (or ``lasio.LASFile``), as I think that might complicate things.

**Comment by kwinkunks** [comment]
This is done, from striplog's point of view. Closing.
