### ISSUE TITLE
Load more properties from CSV

### ISSUE THREAD

**Issue by kwinkunks** [agile-geoscience/striplog#55]
Right now we only support top, base, description, but it wouldn't be too hard to allow more properties. 

The code is a bit gross, so could use cleaning up anyway.  Pretty sure most of it is just doing the work of DictReader...

**Comment by kwinkunks** [comment]
Calling this a bug, the code needs refactoring.

Should support loading arbitrary data.

**Comment by mtb-za** [comment]
Closing this in favour of #128; the issues are essentially the same. Currently we add arbitrary new columns to `data` anyway, even if we do not actually do anything special with that. cf #60 which also discusses this.

**Comment by mtb-za** [comment]
Closing this in favour of #128; the issues are essentially the same. Currently we add arbitrary new columns to data anyway, even if we do not actually do anything special with that. cf #60 which also discusses this.

We do still need to discuss what other aliases we might actually want, but that should happen in #128....
