### ISSUE TITLE
Should interval data belong to Interval or its component(s)?

### ISSUE THREAD

**Issue by kwinkunks** [agile-geoscience/striplog#60]
If I add GR data, eg drawn from a log, to a Striplog, should it be added to the Intervals at the interval level, or should it belong to the (primary) component?
### Interval

Means adding a new attribute to the `Interval` object, maybe a `data` dictionary? 
### Component

![image](https://cloud.githubusercontent.com/assets/1692372/12267421/67112dbe-b91e-11e5-9b3a-f1e92b710646.png)

Question for Fraser I think.

**Comment by EvanBianco** [comment]
Perhaps another way to describe the use case is, "I want to slice into the values of gamma ray according to such and such top(s) and base(s)". So maybe the component doesn't need to hold the log data values per se, but is able to sort-of indexing into the measured depth values to get the values of the log.

If you add GR data to the component, it would also need to describe the position (measured depth) of each of the samples, no? so maybe GR needs to be represented as two arrays, MD and GR values within a single component.  This maybe isn't so bad if we are dealing with regularize samples, in which case the first position, and sample spacing, would be all that is required, but in the case of say doing a hand held Gamma Ray measurement on outcrop or core, say. That would require a position along with each value; which I feel like might be better to store in it's entirety in the log.

**Comment by mtb-za** [comment]
It looks like this might be ready to be closed? There is a `data` dictionary associated with Intervals, although I am not sure that it can hold something like a segment of a GR log unless that is already given to it.

**Comment by kwinkunks** [comment]
Agree Martin. It can just about satisfy this use case, albeit without having a great solution for the handheld GR example, because you'd have to store that as 2 arrays right now (or a 2-column array, or Pandas series, or whatever).
